ROOT=../../../../..
STYLESHEET=$(ROOT)/styles/main.css
FILE=exam

all:
#	rst2html --link-stylesheet --stylesheet-path main.css $(FILE).txt  $(FILE).html
	rst2html  --stylesheet-path $(STYLESHEET) $(FILE).txt  $(FILE).html
